# permissions for end users to edit mongobackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongobackup-editor-role
rules:
- apiGroups:
  - backup.16cloud.online
  resources:
  - mongobackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.16cloud.online
  resources:
  - mongobackups/status
  verbs:
  - get
