# permissions for end users to view mongobackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongobackup-viewer-role
rules:
- apiGroups:
  - backup.16cloud.online
  resources:
  - mongobackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.16cloud.online
  resources:
  - mongobackups/status
  verbs:
  - get
