apiVersion: backup.16cloud.online/v1alpha1
kind: MongoBackup
metadata:
  name: majotest
spec:
  host: mongo-mongodb
  database: test
  schedule: "* * * * *"
  rcloneConfig: "W21ham9dCnR5cGUgPSBzMwpwcm92aWRlciA9IFdhc2FiaQplbnZfYXV0aCA9IGZhbHNlCmFjY2Vzc19rZXlfaWQgPSBaSUtCUjZBNzhOOTFISUdGSFJJQQpzZWNyZXRfYWNjZXNzX2tleSA9IFpLbUU0TDljOVMxVmpnUjhGaE00bmVsSUhMN2NWa2xwc3dGVkozWXoKcmVnaW9uID0gdXMtZWFzdC0xCmVuZHBvaW50ID0gczMud2FzYWJpc3lzLmNvbQoK"
  destination:
    path: "majo:majooperator.test/"
